# Generated by Django 3.2 on 2024-11-20 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Anio', '__first__'),
        ('Mes', '__first__'),
        ('Valor', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_estacionalidad', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RamaPrivado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rama', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RemuneracionRama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remuneracion', models.CharField(max_length=200)),
                ('variacion_interanual', models.CharField(max_length=200)),
                ('variacion_intermensual', models.CharField(max_length=200)),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Anio.anio')),
                ('estacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sector_privado.estacionalidad')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Mes.mes')),
                ('rama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sector_privado.ramaprivado')),
                ('valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Valor.valor')),
            ],
        ),
        migrations.CreateModel(
            name='IndicadoresPrivado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variacion_interanual', models.CharField(max_length=200)),
                ('variacion_intermensual', models.CharField(max_length=200)),
                ('diferencia_interanual', models.CharField(max_length=200)),
                ('diferencia_intermensual', models.CharField(max_length=200)),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Anio.anio')),
                ('estacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sector_privado.estacionalidad')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Mes.mes')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sector_privado.tipodato')),
                ('valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Valor.valor')),
            ],
        ),
        migrations.CreateModel(
            name='CantidadesPrivado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=200)),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Anio.anio')),
                ('estacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sector_privado.estacionalidad')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Mes.mes')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sector_privado.tipodato')),
                ('valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Valor.valor')),
            ],
        ),
        migrations.CreateModel(
            name='AsalariadoRama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=200)),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Anio.anio')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Mes.mes')),
                ('rama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sector_privado.ramaprivado')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Valor.trimestre')),
                ('valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Valor.valor')),
            ],
        ),
    ]
