# Generated by Django 3.2 on 2024-12-10 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Anio', '__first__'),
        ('Mes', '__first__'),
        ('Valor', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demanda', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RefsaUsuarioVariacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variacion_bimestral', models.CharField(max_length=200)),
                ('variacion_anual', models.CharField(max_length=200)),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Anio.anio')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Mes.mes')),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Energia.tarifa')),
                ('valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Valor.valor')),
            ],
        ),
        migrations.CreateModel(
            name='RefsaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usuario', models.CharField(max_length=200)),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Anio.anio')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Mes.mes')),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Energia.tarifa')),
                ('valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Valor.valor')),
            ],
        ),
        migrations.CreateModel(
            name='CammesaVarDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variacion_mensual', models.CharField(max_length=200)),
                ('variacion_anual', models.CharField(max_length=200)),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Anio.anio')),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Energia.demanda')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Mes.mes')),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Energia.tarifa')),
                ('valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Valor.valor')),
            ],
        ),
        migrations.CreateModel(
            name='CammesaDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=200)),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Anio.anio')),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Energia.demanda')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Mes.mes')),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Energia.tarifa')),
                ('valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Valor.valor')),
            ],
        ),
    ]
